CC = gcc
CFLAGS = -Wall -Wextra -std=c99
OBJS = main.o char.o integer.o my_string.o
TARGET = first_lab

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) -o $(TARGET)

main.o: main.c my_string.h
	$(CC) $(CFLAGS) -c main.c

char.o: char.c char.h
	$(CC) $(CFLAGS) -c char.c

integer.o: integer.c integer.h
	$(CC) $(CFLAGS) -c integer.c

my_string.o: my_string.c my_string.h
	$(CC) $(CFLAGS) -c my_string.c

clean:
	rm -f *.o $(TARGET)
