all: first_lab

first_lab: main.o char.o my_string.o
	gcc main.o char.o my_string.o -o first_lab

main.o: main.c my_string.h
	gcc -c main.c

char.o: char.c char.h
	gcc -c char.c

my_string.o: my_string.c my_string.h
	gcc -c my_string.c

clean:
	rm -f *o first_lab
